-- Task 1
CREATE TABLESPACE myTBS1 DATAFILE 'mytbs1_datafile.dbf' SIZE 1M EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
CREATE TABLESPACE myTBS2 DATAFILE 'mytbs2_datafile.dbf' SIZE 1M EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
CREATE TABLESPACE myTBS3 DATAFILE 'mytbs3_datafile.dbf' SIZE 1M EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

-- Task 2 
CREATE USER myDBMS2_LAB2 IDENTIFIED BY myDBMS2_LAB2 DEFAULT TABLESPACE myTBS1 QUOTA 1M ON myTBS1;

-- Task 3
CREATE TABLE myDEPARTMENT (
    DEPT_ID NUMBER(2),
    DEPT_NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPT_ID)
) TABLESPACE myTBS1;

CREATE TABLE mySTUDENT (
    STUDENT_ID NUMBER(20),
    STUDENT_NAME VARCHAR2(40) NOT NULL,
    DEPT_ID NUMBER(2),
    CONSTRAINT STUDENT_ID_PK PRIMARY KEY (STUDENT_ID),
    CONSTRAINT STUDENT_DEPT_ID_FK FOREIGN KEY (DEPT_ID) REFERENCES myDEPARTMENT(DEPT_ID)
) TABLESPACE myTBS1;

-- Task 4
CREATE TABLE myCOURSE (
    COURSE_CODE NUMBER(10),
    COURSE_NAME VARCHAR2(30) NOT NULL,
    CREDIT NUMBER(2),
    DEPT_ID NUMBER(2),
    CONSTRAINT COURSE_CODE_PK PRIMARY KEY (COURSE_CODE),
    CONSTRAINT COURSE_DEPT_ID_FK FOREIGN KEY (DEPT_ID) REFERENCES myDEPARTMENT(DEPT_ID)
) TABLESPACE myTBS2;

-- Task 5
INSERT INTO myDEPARTMENT VALUES (1, 'CSE');

INSERT INTO mySTUDENT VALUES (1, 'STUDENT1', 1);
INSERT INTO mySTUDENT VALUES (2, 'STUDENT2', 1);
INSERT INTO mySTUDENT VALUES (3, 'STUDENT3', 1);
INSERT INTO mySTUDENT VALUES (4, 'STUDENT4', 1);
INSERT INTO mySTUDENT VALUES (5, 'STUDENT5', 1);

INSERT INTO myCOURSE VALUES (1, 'COURSE1', 3, 1);
INSERT INTO myCOURSE VALUES (2, 'COURSE2', 3, 1);
INSERT INTO myCOURSE VALUES (3, 'COURSE3', 3, 1);
INSERT INTO myCOURSE VALUES (4, 'COURSE4', 3, 1);
INSERT INTO myCOURSE VALUES (5, 'COURSE5', 3, 1);

-- Task 6
SELECT COURSE_NAME, myDEPARTMENT.DEPT_NAME
FROM myCOURSE
JOIN myDEPARTMENT ON myCOURSE.DEPT_ID = myDEPARTMENT.DEPT_ID;

-- Task 7
SELECT TABLESPACE_NAME, BYTES / 1024 / 1024 AS MB
FROM DBA_FREE_SPACE WHERE TABLESPACE_NAME IN ('myTBS1', 'myTBS2');

-- Task 8
ALTER TABLESPACE myTBS1 ADD DATAFILE 'mytbs1_2.dbf' SIZE 1M;
ALTER TABLESPACE myTBS1 ADD DATAFILE 'mytbs1_3.dbf' SIZE 1M;

-- Task 9
ALTER DATABASE DATAFILE 'mytbs2_datafile.dbf' RESIZE 4M;

-- Task 10
SELECT TABLESPACE_NAME, BYTES / 1024 / 1024 AS MB
FROM DBA_DATA_FILES WHERE TABLESPACE_NAME IN ('myTBS1', 'myTBS2');

-- Task 11
ALTER TABLESPACE myTBS1 OFFLINE;

-- Task 12
DROP TABLESPACE myTBS1 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

-- Task 13
DROP TABLESPACE myTBS2 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
